apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus
  namespace: test2
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: test-application
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: devfile-sample-code-with-quarkus
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: devfile-sample-code-with-quarkus-
      namespace: test2
    spec:
      params:
      - name: git-url
        value: https://github.com/devfile-samples/devfile-sample-code-with-quarkus
      - name: output-image
        value: quay.io/redhat-appstudio/user-workload:test2-devfile-sample-code-with-quarkus-$(tt.params.git-revision)
      - name: dockerfile
        value: src/main/docker/Dockerfile.jvm.staged
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/mkovarik/hacbs-templates-bundle:2022-05-09-102619
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: devfile-sample-code-with-quarkus/$(tt.params.git-revision)
      - name: registry-auth
        secret:
          secretName: redhat-appstudio-registry-pull-secret
    status: {}
status: {}
